import type { PortfolioData } from "../data/schema";
import { createResumeProjection, type ResumeProjection } from "./create-resume-projection";
import { escapeLatex } from "./escape-latex";

type Profile = ResumeProjection["profile"];
type Experience = ResumeProjection["experience"];
type Skills = ResumeProjection["skills"];
type Education = ResumeProjection["education"];

function renderProfile(profile: Profile) {
  return [
    `\\newcommand{\\resumeName}{${escapeLatex(profile.name)}}`,
    `\\newcommand{\\resumePhone}{${escapeLatex(profile.phone)}}`,
    `\\newcommand{\\resumeEmail}{${escapeLatex(profile.email)}}`,
    `\\newcommand{\\resumeRole}{${escapeLatex(profile.role)}}`,
    `\\newcommand{\\resumeFocus}{${escapeLatex(profile.focus)}}`,
    `\\newcommand{\\resumeLocation}{${escapeLatex(profile.location)}}`,
    `\\newcommand{\\resumeGithubUrl}{${escapeLatex(profile.github)}}`,
    `\\newcommand{\\resumeGithubLabel}{${escapeLatex(profile.githubLabel)}}`,
    `\\newcommand{\\resumeLinkedinUrl}{${escapeLatex(profile.linkedin)}}`,
    `\\newcommand{\\resumeLinkedinLabel}{${escapeLatex(profile.linkedinLabel)}}`,
  ];
}

function renderSummary(summary: string) {
  return [
    "%-----------SUMMARY-----------------",
    "\\section{\\textbf{Summary}}",
    "\\begingroup",
    "\\raggedright",
    "\\hyphenpenalty=10000",
    "\\exhyphenpenalty=10000",
    escapeLatex(summary),
    "\\par",
    "\\endgroup",
  ];
}

function renderExperience(experience: Experience) {
  const lines = [
    "%-----------EXPERIENCE-----------------",
    "\\section{\\textbf{Experience}}",
    "\\resumeSubHeadingListStart",
  ];

  for (const company of experience) {
    lines.push(
      `\\resumeCompany{${escapeLatex(company.company)}}{${escapeLatex(company.location)}}{`,
      ...company.positions.map((position) =>
        `    \\resumePosition{${escapeLatex(position.title)}}{${escapeLatex(position.dates)}}`,
      ),
      "}",
      "\\resumeItemListStart",
      ...company.bullets.map((bullet) => `    \\item{${escapeLatex(bullet)}}`),
      "\\resumeItemListEnd",
      ...company.recognition.map((recognition) =>
        `\\noindent\\hspace{3ex}\\small{\\textbf{Recognition:} ${escapeLatex(recognition)}}`,
      ),
    );
  }

  lines.push("\\resumeSubHeadingListEnd", "\\vspace{-3mm}");
  return lines;
}

function renderSkills(skills: Skills) {
  return [
    "%-----------TECHNICAL SKILLS-----------------",
    "\\section{\\textbf{Technical Skills}}",
    "\\begin{itemize}[leftmargin=0.05in, label={}, noitemsep, topsep=1mm]",
    ...skills.map((skill) =>
      `\\item{\\textbf{${escapeLatex(skill.name)}}{: ${escapeLatex(skill.items.join(", "))}}}`,
    ),
    "\\end{itemize}",
    "\\vspace{0mm}",
  ];
}

function renderEducation(education: Education) {
  return [
    "%-----------EDUCATION-----------------",
    "\\section{\\textbf{Education}}",
    "\\resumeSubHeadingListStart",
    ...education.flatMap((item) => [
      "\\resumeSubheading",
      `  {${escapeLatex(item.institution)}}{CGPA: \\textbf{${escapeLatex(item.cgpa)}}}`,
      `  {${escapeLatex(item.degree)}}{${escapeLatex(item.dates)}}`,
    ]),
    "\\resumeSubHeadingListEnd",
    "\\vspace{-1mm}",
  ];
}

export function renderResume(data: PortfolioData) {
  const resume = createResumeProjection(data);
  return [
    "% Generated from data/portfolio/*.json by scripts/generate-resume.ts.",
    "% Do not edit this file directly.",
    ...renderProfile(resume.profile),
    "",
    "\\input{source/header}",
    "",
    ...renderSummary(resume.profile.summary),
    "",
    ...renderExperience(resume.experience),
    "",
    ...renderSkills(resume.skills),
    "",
    ...renderEducation(resume.education),
    "",
  ].join("\n");
}
