import type { PortfolioData } from "../data/schema";
import { resumeSections } from "./section-order";
import { renderProfileSection } from "./sections/profile";

export function renderResume(data: PortfolioData) {
  return [
    "% Generated from data/portfolio/*.json by scripts/generate-resume.ts.",
    "% Do not edit this file directly.",
    ...renderProfileSection(data.profile),
    "",
    "\\input{source/header}",
    "",
    ...resumeSections.flatMap((renderSection) => [...renderSection(data), ""]),
  ].join("\n");
}
