import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { portfolio } from "../src/data/portfolio";
import type { PortfolioData } from "../src/data/schema";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const outputPath = resolve(projectRoot, "build/generated/resume-content.tex");

export function escapeLatex(value: unknown) {
  const replacements: Record<string, string> = {
    "\\": "\\textbackslash{}",
    "{": "\\{",
    "}": "\\}",
    "%": "\\%",
    "$": "\\$",
    "&": "\\&",
    "#": "\\#",
    "_": "\\_",
    "^": "\\textasciicircum{}",
    "~": "\\textasciitilde{}",
  };
  return String(value)
    .replace(/[\\{}%$&#_^~]/g, (character) => replacements[character] ?? character)
    .replaceAll("–", "--")
    .replaceAll("—", "---")
    .replaceAll("’", "'");
}

export function renderResume(data: PortfolioData) {
  const line = (value: unknown) => escapeLatex(value);
  const profile = data.profile;
  const output = [
    "% Generated from data/portfolio/*.json by scripts/generate-resume.ts.",
    "% Do not edit this file directly.",
    `\\newcommand{\\resumeName}{${line(profile.name)}}`,
    `\\newcommand{\\resumePhone}{${line(profile.phone)}}`,
    `\\newcommand{\\resumeEmail}{${line(profile.email)}}`,
    `\\newcommand{\\resumeRole}{${line(profile.role)}}`,
    `\\newcommand{\\resumeFocus}{${line(profile.focus)}}`,
    `\\newcommand{\\resumeLocation}{${line(profile.location)}}`,
    `\\newcommand{\\resumeGithubUrl}{${line(profile.github)}}`,
    `\\newcommand{\\resumeGithubLabel}{${line(profile.githubLabel)}}`,
    `\\newcommand{\\resumeLinkedinUrl}{${line(profile.linkedin)}}`,
    `\\newcommand{\\resumeLinkedinLabel}{${line(profile.linkedinLabel)}}`,
    "",
    "\\input{source/header}",
    "",
    "%-----------SUMMARY-----------------",
    "\\section{\\textbf{Summary}}",
    "\\begingroup",
    "\\raggedright",
    "\\hyphenpenalty=10000",
    "\\exhyphenpenalty=10000",
    line(profile.resumeSummary),
    "\\par",
    "\\endgroup",
    "",
    "%-----------EXPERIENCE-----------------",
    "\\section{\\textbf{Experience}}",
    "\\resumeSubHeadingListStart",
  ];

  for (const company of data.companies) {
    const positions = data.positions.filter((position) => position.companyId === company.id);
    const work = data.professionalWork.filter((item) => item.companyId === company.id);
    if (!positions.length || !work.length) continue;
    output.push(
      `\\resumeCompany{${line(company.name)}}{${line(company.location)}}{`,
      ...positions.map((position) => `    \\resumePosition{${line(position.title)}}{${line(position.resumeDates)}}`),
      "}",
      "\\resumeItemListStart",
      ...work.map((item) => `    \\item{${line(item.resumeBullet)}}`),
      "\\resumeItemListEnd",
    );
    const recognition = data.recognition.filter((item) => item.companyId === company.id && item.resumeText);
    for (const item of recognition) output.push(`\\noindent\\hspace{3ex}\\small{\\textbf{Recognition:} ${line(item.resumeText)}}`);
  }

  output.push(
    "\\resumeSubHeadingListEnd",
    "\\vspace{-3mm}",
    "",
    "%-----------TECHNICAL SKILLS-----------------",
    "\\section{\\textbf{Technical Skills}}",
    "\\begin{itemize}[leftmargin=0.05in, label={}, noitemsep, topsep=1mm]",
    ...data.skills.map((skill) => `\\item{\\textbf{${line(skill.resumeGroup)}}{: ${line((skill.resumeItems ?? skill.items).join(", "))}}}`),
    "\\end{itemize}",
    "\\vspace{0mm}",
    "",
    "%-----------EDUCATION-----------------",
    "\\section{\\textbf{Education}}",
    "\\resumeSubHeadingListStart",
    ...data.education.flatMap((education) => [
      "\\resumeSubheading",
      `  {${line(education.institution)}}{CGPA: \\textbf{${line(education.cgpa)}}}`,
      `  {${line(education.degree)}}{${education.startYear} - ${education.endYear}}`,
    ]),
    "\\resumeSubHeadingListEnd",
    "\\vspace{-1mm}",
    "",
  );
  return output.join("\n");
}

async function main() {
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderResume(portfolio), "utf8");
  process.stdout.write(`Generated ${outputPath}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
