import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const dataPath = resolve(projectRoot, "data/portfolio.json");
const outputPath = resolve(projectRoot, "build/generated/resume-content.tex");

export function escapeLatex(value) {
  const replacements = {
    "\\": "\\textbackslash{}",
    "{": "\\{",
    "}": "\\}",
    "%": "\\%",
    "$": "\\$",
    "&": "\\&",
    "#": "\\#",
    "_": "\\_",
    "^": "\\textasciicircum{}",
    "~": "\\textasciitilde{}",
  };
  return String(value)
    .replace(/[\\{}%$&#_^~]/g, (character) => replacements[character])
    .replaceAll("–", "--")
    .replaceAll("—", "---")
    .replaceAll("’", "'");
}

export function validatePortfolio(data) {
  const requiredArrays = ["companies", "positions", "professionalWork", "projects", "skills", "recognition", "education"];
  for (const key of requiredArrays) {
    if (!Array.isArray(data[key]) || data[key].length === 0) throw new Error(`${key} must be a non-empty array.`);
  }

  const companyIds = new Set(data.companies.map((company) => company.id));
  if (companyIds.size !== data.companies.length) throw new Error("Company ids must be unique.");
  for (const item of [...data.positions, ...data.professionalWork]) {
    if (!companyIds.has(item.companyId)) throw new Error(`Unknown company id ${item.companyId}.`);
  }
  if (new Set(data.positions.map((position) => position.id)).size !== data.positions.length) throw new Error("Position ids must be unique.");
  if (new Set(data.professionalWork.map((work) => work.id)).size !== data.professionalWork.length) throw new Error("Professional work ids must be unique.");
  if (data.professionalWork.some((work) => !work.resumeBullet)) throw new Error("Every professional work record needs a resumeBullet.");
}

export function renderResume(data) {
  validatePortfolio(data);
  const line = (value) => escapeLatex(value);
  const profile = data.profile;
  const output = [
    "% Generated from data/portfolio.json by scripts/generate-resume.mjs.",
    "% Do not edit this file directly.",
    `\\newcommand{\\resumeName}{${line(profile.name)}}`,
    `\\newcommand{\\resumePhone}{${line(profile.phone)}}`,
    `\\newcommand{\\resumeEmail}{${line(profile.email)}}`,
    `\\newcommand{\\resumeRole}{${line(profile.role)}}`,
    `\\newcommand{\\resumeFocus}{${line(profile.focus)}}`,
    `\\newcommand{\\resumeLocation}{${line(profile.location)}}`,
    `\\newcommand{\\resumeGithubUrl}{${line(profile.github)}}`,
    `\\newcommand{\\resumeGithubLabel}{${line(profile.githubLabel)}}`,
    `\\newcommand{\\resumeLinkedinUrl}{${line(profile.linkedin)}}`,
    `\\newcommand{\\resumeLinkedinLabel}{${line(profile.linkedinLabel)}}`,
    "",
    "\\input{source/header}",
    "",
    "%-----------SUMMARY-----------------",
    "\\section{\\textbf{Summary}}",
    "\\begingroup",
    "\\raggedright",
    "\\hyphenpenalty=10000",
    "\\exhyphenpenalty=10000",
    line(profile.resumeSummary),
    "\\par",
    "\\endgroup",
    "",
    "%-----------EXPERIENCE-----------------",
    "\\section{\\textbf{Experience}}",
    "\\resumeSubHeadingListStart",
  ];

  for (const company of data.companies) {
    const positions = data.positions.filter((position) => position.companyId === company.id);
    const work = data.professionalWork.filter((item) => item.companyId === company.id);
    if (!positions.length || !work.length) continue;
    output.push(
      `\\resumeCompany{${line(company.name)}}{${line(company.location)}}{`,
      ...positions.map((position) => `    \\resumePosition{${line(position.title)}}{${line(position.resumeDates)}}`),
      "}",
      "\\resumeItemListStart",
      ...work.map((item) => `    \\item{${line(item.resumeBullet)}}`),
      "\\resumeItemListEnd",
    );
    const recognition = data.recognition.filter((item) => item.companyId === company.id && item.resumeText);
    for (const item of recognition) output.push(`\\noindent\\hspace{3ex}\\small{\\textbf{Recognition:} ${line(item.resumeText)}}`);
  }

  output.push(
    "\\resumeSubHeadingListEnd",
    "\\vspace{-3mm}",
    "",
    "%-----------TECHNICAL SKILLS-----------------",
    "\\section{\\textbf{Technical Skills}}",
    "\\begin{itemize}[leftmargin=0.05in, label={}, noitemsep, topsep=1mm]",
    ...data.skills.map((skill) => `\\item{\\textbf{${line(skill.resumeGroup)}}{: ${line((skill.resumeItems ?? skill.items).join(", "))}}}`),
    "\\end{itemize}",
    "\\vspace{0mm}",
    "",
    "%-----------EDUCATION-----------------",
    "\\section{\\textbf{Education}}",
    "\\resumeSubHeadingListStart",
    ...data.education.flatMap((education) => [
      "\\resumeSubheading",
      `  {${line(education.institution)}}{CGPA: \\textbf{${line(education.cgpa)}}}`,
      `  {${line(education.degree)}}{${education.startYear} - ${education.endYear}}`,
    ]),
    "\\resumeSubHeadingListEnd",
    "\\vspace{-1mm}",
    "",
  );
  return output.join("\n");
}

async function main() {
  const data = JSON.parse(await readFile(dataPath, "utf8"));
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderResume(data), "utf8");
  process.stdout.write(`Generated ${outputPath}\n`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
